dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer update

script:
  - php vendor/bin/phpunit -c test/phpunit.xml
  - php vendor/bin/phpcs --standard=./test/codesniffer.xml --encoding=utf-8 --extensions=php -p -s lib
  - php phpstan.phar analyze -c ./phpstan.neon -l 4 lib
  - php vendor/bin/infection --log-verbosity=2
  - cat infection-log.txt
